baseURL = "http://charlesgeng.github.io/"
languageCode = "zh-cn"
title = "Charles Geng's Web"
theme = "mainroad"
disqusShortname = "charlesgeng-github-io" # Enable Disqus comments by entering your Disqus shortname

[Author] # Used in authorbox
  name = "Charles Geng"
  bio = "This is not a technology only. 这不仅仅是一个技术博客。"


[Params]
toc = true
authorbox = true

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5
  tags_counter = true



[Params.widgets.social]
  # Enable parts of social widget
  linkedin = "gengqi"
  github = "charlesgeng"

[[Params.widgets.social.custom]]
  title = "LeetCode"
  url = "https://LeetCode.com/CharlesGeng"
  icon = "leetcode.svg"  # Optional. Path relative to "layouts/partials"


[menu]
  [[menu.main]]
    name = "blog"
    pre = "<i class='fa fa-road'></i>"
    url = "/post/"
    weight = -100
